name: Your Action Name

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Load config.json
        id: load-config
        run: |
          import json
          with open('config.json') as f:
              config = json.load(f)
          print(f"::set-output name=repo_owner::{config['repo_owner']}")
          print(f"::set-output name=repo_name::{config['repo_name']}")

      - name: Run your script
        env:
          repo_owner: ${{ steps.load-config.outputs.repo_owner }}
          repo_name: ${{ steps.load-config.outputs.repo_name }}
        run: |
          # Your script here, using repo_owner and repo_name
