name: Respond to Ollama Query

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ollama
        run: |
          echo "Installing Ollama..."
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Verify Ollama Installation
        run: |
          echo "Verifying Ollama installation..."
          ollama --version  # Check if Ollama is installed correctly

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Ollama Service
        run: |
          echo "Starting Ollama service..."
          nohup ollama serve &  # Start the Ollama service in the background

      - name: Run the Ollama interactor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running Ollama interactor for issue number ${{ github.event.issue.number }}"
          python ollama_interactor.py ${{ github.event.issue.number }}
