name: Issue Checker and Model Runner

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Extract Model and Query
        id: extract_info
        run: |
          MODEL_NAME="${{ github.event.issue.title }}"
          QUERY="${{ github.event.issue.body }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"

          echo "Model Name: $MODEL_NAME"
          echo "Query: $QUERY"
          echo "Issue Number: $ISSUE_NUMBER"

          echo "MODEL_NAME=$MODEL_NAME" >> $GITHUB_ENV
          echo "QUERY=$QUERY" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Run the Selected Model
        id: run_model
        run: |
          echo "Running model: $MODEL_NAME"
          echo "Using query: $QUERY"
          RESPONSE=$(ollama run "$MODEL_NAME" --query "$QUERY" 2>&1)

          echo "Response: $RESPONSE"
          echo "RESPONSE=$RESPONSE" >> $GITHUB_ENV

      - name: Append to CSV
        run: |
          python <<EOF
          import pandas as pd

          file_path = "issues_log.csv"
          data = {
              "Issue Number": ["${{ env.ISSUE_NUMBER }}"],
              "Question": ["${{ env.QUERY }}"],
              "Response": ["${{ env.RESPONSE }}"]
          }

          df = pd.DataFrame(data)
          try:
              existing_df = pd.read_csv(file_path)
              df = pd.concat([existing_df, df], ignore_index=True)
          except FileNotFoundError:
              pass

          df.to_csv(file_path, index=False)
          EOF

      - name: Commit and Push CSV
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: issues_log.csv
          commit_message: "Update issues log with new response"
